#ifndef _SALTICIDAE_CONFIG_H
#define _SALTICIDAE_CONFIG_H

/* #undef SALTICIDAE_DEBUG_LOG */
/* #undef SALTICIDAE_NORMAL_LOG */
/* #undef SALTICIDAE_MSG_STAT */
/* #undef SALTICIDAE_NOCHECK */
/* #undef SALTICIDAE_NOCHECKSUM */
#define SALTICIDAE_CBINDINGS

#endif
